Libalternatives support
openSUSE/python-rpm-macros pull request #115
Opened 2021-09-28 14:08 UTC by schubi2

Please have a look to the README.md how the patch supports the new libalternatives too.

2021-09-29 08:45 UTC, bnavigator reviewed
Do you have any demo packages where this works?

2021-09-29 08:45 UTC, bnavigator commented on flavor.in
> +    print(rpm.expand("%ghost %{_datadir}/libalternatives/" .. name .. "/10%python_version_nodots.conf\\\n")) \
This does not look right. It's either one or the other, but not both files for any flavor. Have a look at the `prio` variable in `python_install_alternative`.

Also, the Python 3.10 flavor, once it is primary (not that soon I guess), it will have a prio of 1310, not 10310.

2021-09-29 09:15 UTC, mcepl requested changes
Generally I don't see any serious problems, aside from what Ben noticed.

2021-09-29 09:15 UTC, mcepl commented on README.md
> +  ```spec
Wouldn't it be good idea to make this into one macro? Something like `libalternatives_requires`? It looks quite repetitive to me.

2021-09-29 12:34 UTC, bnavigator commented on README.md
> +  ```spec
Putting it into a macro makes it inaccessible to the build service, which needs to resolve the `BuildRequires` before starting the rpmbuild job.

2021-09-29 14:36 UTC, schubi2 commented on flavor.in
> +    print(rpm.expand("%ghost %{_datadir}/libalternatives/" .. name .. "/10%python_version_nodots.conf\\\n")) \
At least it is not really nice :-) I have fixed it.

2021-09-29 14:36 UTC, schubi2 commented on README.md
> +  This example shows that *libalterntive* is available for TW only.
Thanks.

2021-09-29 14:37 UTC, schubi2 commented on README.md
> +  ```spec
Somehow I cannot manage it via a macro. The requirement will not be written. Sorry....

2021-09-29 14:44 UTC, bnavigator commented on flavor.in
> +    end \
How about factoring this out into a function instead of duplicating code?

2021-09-29 19:47 UTC, schubi2 commented on flavor.in
> +    end \
Yes, sounds good.

2021-09-29 19:47 UTC, schubi2 commented on flavor.in
> +    end \
done

2021-09-30 06:18 UTC, schubi2 commented
Currently I am testing with following packages:
python-tempora - simple example
python-evtx - has multiple calls
python-ipython - has man pages and group settings
I will also transfer and testing following packages (needed for MicoOS):
https://build.opensuse.org/package/show/openSUSE:Factory/python-chardet
https://build.opensuse.org/package/show/openSUSE:Factory/python-cheroot
https://build.opensuse.org/package/show/openSUSE:Factory/python-CherryPy
https://build.opensuse.org/package/show/openSUSE:Factory/python-numpy
https://build.opensuse.org/package/show/openSUSE:Factory/python-Flask
https://build.opensuse.org/package/show/openSUSE:Factory/python-pecan
https://build.opensuse.org/package/show/openSUSE:Factory/python-jsonpatch
https://build.opensuse.org/package/show/openSUSE:Factory/python-jsonpointer
https://build.opensuse.org/package/show/openSUSE:Factory/python-jsonschema
https://build.opensuse.org/package/show/openSUSE:Factory/python-Mako
https://build.opensuse.org/package/show/openSUSE:Factory/python-Babel
https://build.opensuse.org/package/show/openSUSE:Factory/python-pybind11
https://build.opensuse.org/package/show/openSUSE:Factory/python-rsa
https://build.opensuse.org/package/show/openSUSE:Factory/python-rtslib-fb
https://build.opensuse.org/package/show/openSUSE:Factory/python-waitress
https://build.opensuse.org/package/show/openSUSE:Factory/python-websocket-client
https://build.opensuse.org/package/show/openSUSE:Factory/python-pysmi
https://build.opensuse.org/package/show/openSUSE:Factory/python-ipython (mit man pages)
https://build.opensuse.org/package/show/openSUSE:Factory/python-jupyter-core
https://build.opensuse.org/package/show/openSUSE:Factory/python-notebook
https://build.opensuse.org/package/show/openSUSE:Factory/python-nbclassic
https://build.opensuse.org/package/show/openSUSE:Factory/python-jupyter-server
https://build.opensuse.org/package/show/openSUSE:Factory/python-nbformat
https://build.opensuse.org/package/show/openSUSE:Factory/python-pip
https://build.opensuse.org/package/show/openSUSE:Factory/python-pytest
https://build.opensuse.org/package/show/openSUSE:Factory/python-Pygments
https://build.opensuse.org/package/show/openSUSE:Factory/python-json5
https://build.opensuse.org/package/show/openSUSE:Factory/python-wheel

2021-09-30 07:23 UTC, schubi2 commented
If you want I can continue with the other packages and after I have converted and tested them we are quite sure that it is working and can merge the PR after it.

2021-10-01 08:28 UTC, schubi2 commented
I have changed and tested all mentioned packages without a problem. Could we please finish this PR in order to submit all these packages ?

2021-10-01 08:34 UTC, bnavigator commented on README.md
> +[Libalterntive](https://github.com/openSUSE/libalternatives) provides another way for settings alternative.
```suggestion
[Libalternative](https://github.com/openSUSE/libalternatives) provides another way for settings alternative.
```

2021-10-01 08:38 UTC, bnavigator commented
> Currently I am testing with following packages:
> python-tempora - simple example
> python-evtx - has multiple calls
> python-ipython - has man pages and group settings

Where is the obs repo demonstrating it? home:schubi2 does not have your modified python-rpm-macros and none of the above packages' specfiles look like they already fully use the macros.

2021-10-01 08:39 UTC, schubi2 commented on README.md
> +[Libalterntive](https://github.com/openSUSE/libalternatives) provides another way for settings alternative.
Somehow I have problems with this name :-)

2021-10-01 10:05 UTC, schubi2 commented
I have pushed all my changes to home:schubi2.
https://build.opensuse.org/package/show/home:schubi2/python-rpm-macros
https://build.opensuse.org/package/show/home:schubi2/python-evtx
https://build.opensuse.org/package/show/home:schubi2/python-ipython
https://build.opensuse.org/package/show/home:schubi2/python-tempora
And the rest of the 30 packages....

2021-10-01 10:44 UTC, bnavigator commented
> I have pushed all my changes to home:schubi2.
> https://build.opensuse.org/package/show/home:schubi2/python-rpm-macros 

Okay, I see. The service file and the version 20210929.eccf3f2 are not correct, you modified the files manually. Still not in the state of the current PR. You could adjust your _service to fetch from your PR branch.

> https://build.opensuse.org/package/show/home:schubi2/python-evtx 

rpmlint is not happy:

```
[  300s] python36-evtx.noarch: E: update-alternatives-requirement-missing
[  300s] python38-evtx.noarch: E: update-alternatives-requirement-missing
[  300s] python39-evtx.noarch: E: update-alternatives-requirement-missing
[  300s] The package does not have update-alternatives in Requires(post) or
[  300s] Requires(postun). This is needed for the proper scriptlet execution.
[  300s] 
[  300s] python36-evtx.noarch: E: update-alternatives-post-call-missing
[  300s] python38-evtx.noarch: E: update-alternatives-post-call-missing
[  300s] python39-evtx.noarch: E: update-alternatives-post-call-missing
[  300s] The package does not call update-alternatives --install in post phase to
[  300s] install all the configuration.
[  300s] 
```

> https://build.opensuse.org/package/show/home:schubi2/python-ipython 

same

> https://build.opensuse.org/package/show/home:schubi2/python-tempora
Why does the 15.3 build fail? It does not fail in d:l:p.
egg-info version is lost. Is it due to a libalternative related change in a package in the build dep tree?

2021-10-01 11:01 UTC, bnavigator commented
> rpmlint is not happy:

```
> rpm -q --scripts python38-evtx-0.6.1-31.1.noarch.rpm
warning: python38-evtx-0.6.1-31.1.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 3d51bceb: NOKEY
preinstall scriptlet (using /bin/sh):
# If libalternatives is used: Removing old update-alternatives entries.
for c in dump dump_chunk_slack eid_record_numbers extract_record filter_records info record_structure structure templates; do
  

if [ 1 -eq 1 ] ; then 
if [ "$1" -gt 0 ] && [ -f /usr/sbin/update-alternatives ]; then 
    update-alternatives --quiet --remove "evtx_$c.py" "/usr/bin/evtx_$c.py-3.8" 
fi 
fi 

done
postinstall scriptlet (using /bin/sh):
for c in dump dump_chunk_slack eid_record_numbers extract_record filter_records info record_structure structure templates; do
   
mkdir -p /usr/share/libalternatives/evtx_$c.py
echo binary=/usr/bin/evtx_$c.py-3.8 >/usr/share/libalternatives/evtx_$c.py/1038.conf
echo group=evtx_$c.py >>/usr/share/libalternatives/evtx_$c.py/1038.conf

done
postuninstall scriptlet (using /bin/sh):
for c in dump dump_chunk_slack eid_record_numbers extract_record filter_records info record_structure structure templates; do
  

if [ ! -e "/usr/bin/evtx_$c.py-3.8" ] && [ -f /usr/sbin/update-alternatives ]; then 
    update-alternatives --quiet --remove "evtx_$c.py" "/usr/bin/evtx_$c.py-3.8" 
fi 

done
```

You have to either adjust rpmlint or not install any update-alternatives call into `%post` and `%postun` at all.

https://github.com/rpm-software-management/rpmlint/blob/90c84aede91f999c4b4cbd0c3c73d5aa96f54f0f/rpmlint/checks/AlternativesCheck.py#L130

2021-10-01 11:03 UTC, bnavigator commented on README.md
> +  %endif
Strictly speaking, you need a `Requires(pre): update-alternatives` here

2021-10-01 11:27 UTC, mcepl approved these changes

2021-10-01 12:23 UTC, schubi2 commented on README.md
> +  %endif
In the long term we would like to get rid of update-alternatives. We have already discussed this and have removed this requirement and have added a check if the binary update-alternatives exists.

2021-10-01 12:25 UTC, schubi2 commented on README.md
> +  %endif
>Okay, I see. The service file and the version 20210929.eccf3f2 are not correct, you modified the files manually. Still not in the state of the current PR. You could adjust your _service to fetch from your PR branch.

Yes, you are right. I have done this only for testing. When the git PR is merged I would like to generate a complete new obs request from the original git repository.

2021-10-01 14:41 UTC, merged

2021-10-01 14:41 UTC, mcepl commented
@schubi2 Thank you very much and please submit the request to Factory from the current master.

2021-10-01 14:45 UTC, schubi2 commented
Thank you ! But I will also have a look to the rpm-lint. Perhaps we can make it nicer there :-)