Add %<flavor>_fix_shebang macro
openSUSE/python-rpm-macros pull request #155
Opened 2023-02-18 18:36 UTC by bnavigator

As requested in #153 

This macro can be called explicitly as `%python310_fix_shebang`, if you want to have all scripts installed into `%_bindir` executed by `/usr/bin/python3.10`.

It is called implicitly in `%<flavor>_pyproject_install`, **but not in the deprecated `%<flavor>_install`.** The latter would require more effort to implement, because adding lines to the macro would prevent the common pattern to append arguments directly after the currently parameterless macro.

In a `%define pythons python3` build environment, `%python3_fix_shebang` creates the shebang with the resolved symlink where `%{_bindir}/python3` points to. This is the only use case where the macro makes sense. When installing entry-points, Pip and Setuptools normally create the interpreter lines with the same interpreter as they are called by. Thus `python3 setup.py install` (from `%python3_install`) or `python3 -mpip install ...` would create a shebang pointing to `python3`, but the macro fixes it to the current primary interpreter (`/usr/bin/python3.10`).

2023-02-18 18:36 UTC, bnavigator commented
(not tested yet)

2023-03-02 12:11 UTC, danigm requested changes
Besides the `realpath -f` issue, I think we can merge this.

2023-03-02 13:18 UTC, mcepl commented on flavor.in
> +sed -i "1s@#!.*python.*@#!$(realpath -f %__#FLAVOR#)@" %{buildroot}%{_bindir}/*
It is either `realpath` or `readlink -f`, https://unix.stackexchange.com/a/136527

2023-03-03 20:57 UTC, bnavigator commented on flavor.in
> +sed -i "1s@#!.*python.*@#!$(realpath -f %__#FLAVOR#)@" %{buildroot}%{_bindir}/*
Could you please test again? I fixed the realpath call

2023-03-03 22:39 UTC, mcepl commented on flavor.in
> +sed -i "1s@#!.*python.*@#!$(realpath -f %__#FLAVOR#)@" %{buildroot}%{_bindir}/*
Tomorrow, it is a bedtime for me now.

2023-03-04 20:22 UTC, merged

2023-03-04 20:22 UTC, mcepl commented
Thank you.